[
    { "id_bank": "1",
    "initial_row": "2",
    "max_column_number": "11",
    "min_column_number": "9",
    "date_position": "2",
    "reference_position": [5],
    "egress_position": "7", 
    "income_position": "8", 
    "date_format": "m/d/Y" },

    {"id_bank":"2",
    "initial_row":"2",
    "max_column_number":"14",
    "min_column_number":"11",
    "date_position":"2",
    "reference_position":[5,11],
    "egress_position":"9",
    "income_position":"8",
    "date_format":"m/d/Y"},

    {"id_bank":"3",
    "initial_row":"10",
    "max_column_number":"14",
    "min_column_number":"3",
    "date_position":"3",
    "reference_position":[6],
    "egress_position":"9",
    "income_position":"12",
    "date_format":"m/d/Y"},

    {"id_bank":"4",
    "initial_row":"11",
    "max_column_number":"8",
    "min_column_number":"6",
    "date_position":"1",
    "reference_position":[2],
    "egress_position":"4",
    "income_position":"5",
    "date_format":"m/d/Y"},

    {"id_bank":"7",
    "initial_row":"2",
    "max_column_number":"21",
    "min_column_number":"5",
    "date_position":"2",
    "reference_position":[5],
    "egress_position":"7",
    "income_position":"7",
    "date_format":"null"},

    {"id_bank":"14",
    "initial_row":"2",
    "max_column_number":"7",
    "min_column_number":"6",
    "date_position":"1",
    "reference_position":[3,6],
    "egress_position":"4",
    "income_position":"4",
    "date_format":"Y-m-d"},

    {"id_bank":"15",
    "initial_row":"2",
    "max_column_number":"7",
    "min_column_number":"5",
    "date_position":"1",
    "reference_position":[2,6],
    "egress_position":"3",
    "income_position":"4",
    "date_format":"'m/d/Y"},

    {"id_bank":"17",
    "initial_row":"2",
    "max_column_number":"7",
    "min_column_number":"5",
    "date_position":"1",
    "reference_position":[2,6],
    "egress_position":"3",
    "income_position":"4",
    "date_format":"'m/d/Y"},

    {"id_bank":"6",
    "initial_row":"2",
    "max_column_number":"7",
    "min_column_number":"5",
    "date_position":"1",
    "reference_position":[2,6],
    "egress_position":"3",
    "income_position":"4",
    "date_format":"'m/d/Y"}
]
