[
    {"type":"COMISIÓN BANCARIA",
     "subtypes":["COMISIÓN POR RECIBO",
                "COMISIÓN POR SPEI",
                "COMISIÓN POR MENSUALIDAD",
                "COMISIÓN POR DISPERSIÓN",
                "COMISIÓN POR DEPÓSITO",
                "COMISIÓN POR RETIRO",
                "COMISIÓN POR TEF"],
     "examples":["COMISION POR  IVA",
                "COMISION POR  Recibo",
                "COMISION POR TEF Enviado",
                "COMISION POR Retiro",
                "COMISION POR DepÃ³sito",
                "COMISION POR Depósito",
                "ComisiÃ³n  Dispersion",
                "Comisión  Dispersion",
                "ComisiÃ³n  Por Mensualidad",
                "Comisión  Por Mensualidad",
                "COMISION POR  SPEI Enviado",
                "Comision por servicio Banca Electronica",
                "COM SERV BANCOMER",
                "COM SDO INFERIOR",
                "COMISION SPEI",
                "COMISION REGPR",
                "COMISION TOKEN 1"],
     "regex":[]},

     {"type":"CRÉDITO BANCARIO",
     "subtypes":["CRÉDITO"],
     "examples":["Pago Parcial CrÃ©dito",
                "Pago Parcial Crédito"],
     "regex":[]},

     {"type":"DEVOLUCIÓN DE PAGO",
     "subtypes":["DEVOLUCIÓN DE PAGO"],
     "examples":["DevoluciÃ³n de SPEI",
                "Devolución de SPEI"],
     "regex":[]},

     {"type":"DEVOLUCIÓN VIÁTICOS",
     "subtypes":["DEVOLUCIÓN VIÁTICOS"],
     "examples":["",""],
     "regex":[]},

     {"type":"IMPUESTO IVA",
     "subtypes":["IVA"],
     "examples":["IVA COMISION POR",
                "IVA comision Banca Electronica",
                "IVA COM SERVICIOS",
                "IVA COM TRANSACCIONE BNTC",
                "IVA COM SDO INFERIOR",
                "IVA COMI  16%",
                "IVA COMISION SPEI",
                "IVA TOKEN 1"],
     "regex":[]},

     {"type":"INGRESO BANCARIO",
     "subtypes":["INGRESO"],
     "examples":["",""],
     "regex":[]},

     {"type":"INGRESO INTERESES",
     "subtypes":["INTERESES INVERSIÓN"],
     "examples":["",""],
     "regex":[]},

     {"type":"INGRESO VENTA",
     "subtypes":["INGRESO DETALLE",
                "INGRESO MAYOREO",
                "INGRESO DISTRIBUIDORES"],
     "examples":["",""],
     "regex":[]},

     {"type":"MOVIMIENTO NO DEFINIDO",
     "subtypes":["NO DEFINIDO"],
     "examples":["",""],
     "regex":[]},

     {"type":"PAGO BANCARIO",
     "subtypes":["PAGO"],
     "examples":["SPEI Enviado:",
                "Doc. Pagado por Camara de Compensacion",
                "Documento Pagado en Efectivo",
                "Pago de Servicios",
                "Retiro de Recursos",
                "Retiro para deposito en Otra Cuenta",
                "Retiro por Cheque Certificados",
                "Retiro por domiciliacion",
                "Retiro por operacion cambios",
                "Retiro X OperaciÃ³n de Mesa de Dinero",
                "Retiros miscelaneos",
                "SPEI Enviado",
                "Recibo #",
                "Pago de impuestos RFC",
                "PAGO DE NOMINA",
                "TRASPASO A TERCEROS",
                "PAGO DE AGUINALDO",
                "CARGO NOMINA",
                "PAGO -"],
     "regex":[]},

     {"type":"REEMBOLSO NÓMINA",
     "subtypes":["REEMBOLSO NÓMINA"],
     "examples":["",""],
     "regex":[]}
     
]